{
 "title": "Prometheus API Overview",
 "description": "Extended HTTP API service for Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/hayk96/prometheus-api/main/docs/images/logo.png\" width=\"100%\", height=\"100%\" > "
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP status codes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (floor(increase(http_requests_total{job=\"$job\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests details",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method,status,handler) (floor(increase(http_requests_total{job=\"$job\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP methods",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (floor(increase(http_requests_total{job=\"$job\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"$job\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 requests latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le,method,handler))",
     "legendFormat": "{{method}}: {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_size_bytes_sum{job=\"$job\"}[$__rate_interval]))\n/\nsum by (handler) (rate(http_request_size_bytes_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP response size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_response_size_bytes_sum{job=\"$job\"}[$__rate_interval]))\n/\nsum by (handler) (rate(http_response_size_bytes_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}