server:
  sidecarContainers:
     prometheus-api:
       image: hayk96/prometheus-api:latest
       imagePullPolicy: IfNotPresent
       args:
        - --prom.addr=http://localhost:9091
        - --web.listen-address=0.0.0.0:9090
        - --rule.path=/rules
        - --web.enable-ui=true
       ports:
         - name: http
           containerPort: 9090
       volumeMounts:
        - name: storage-volume
          mountPath: /rules
          subPath: rules
          readOnly: false
       startupProbe:
         httpGet:
           path: /health
           port: http
           scheme: HTTP
         initialDelaySeconds: 30
         timeoutSeconds: 1
         periodSeconds: 5
         successThreshold: 1
         failureThreshold: 1
       livenessProbe:
         httpGet:
           path: /health
           port: http
           scheme: HTTP
         initialDelaySeconds: 30
         timeoutSeconds: 1
         periodSeconds: 60
         successThreshold: 1
         failureThreshold: 2
  extraFlags:
    - web.enable-lifecycle
    - web.enable-admin-api
    - web.listen-address=:9091
  extraVolumeMounts:
    - name: storage-volume
      mountPath: /rules
      subPath: rules
serverFiles:
  prometheus.yml:
    rule_files:
      - /rules/*.yml
      - /rules/*.yaml