name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths: [src/**/*, main.py, requirements.txt, Dockerfile]

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dry run for Git tag
        id: git_tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          DRY_RUN: true
          DEFAULT_BUMP: patch
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.git_tag.outputs.tag }}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}-${{ steps.git_tag.outputs.tag }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.git_tag.outputs.tag }}
          path: /tmp/${{ github.event.repository.name }}-${{ steps.git_tag.outputs.tag }}.tar
      - name: Prepare job outputs
        id: op
        run: |
          echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
          echo "app_version=$(sed "s/^v//" <<< ${{ steps.git_tag.outputs.tag }})" >> "$GITHUB_OUTPUT"
    outputs:
       gitTag: ${{ steps.git_tag.outputs.tag }}
       appVersion: ${{ steps.op.outputs.app_version }}
       date: ${{ steps.op.outputs.date }}

  scan:
    name: Scan Docker images
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ needs.build.outputs.gitTag }}
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/${{ github.event.repository.name }}-${{ needs.build.outputs.gitTag }}.tar
      - name: Find vulnerabilities
        run: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock \
          anchore/grype:v0.72.0 docker:${{ github.repository }}:${{ needs.build.outputs.gitTag }} -o table --fail-on critical

  push:
    name: Push Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [build, scan]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ needs.build.outputs.gitTag }}
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/${{ github.event.repository.name }}-${{ needs.build.outputs.gitTag }}.tar
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to the GH Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker images to DockerHub
        run: |
          docker push docker.io/${{ github.repository }}:${{ needs.build.outputs.gitTag }}
          docker push docker.io/${{ github.repository }}:latest
      - name: Push Docker images to GH Container registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ needs.build.outputs.gitTag }}
          docker push ghcr.io/${{ github.repository }}:latest          

  bump:
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    needs: [build, scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Update VERSION file
        run: |
          echo ${{ needs.build.outputs.appVersion }} > VERSION
          git commit -a --no-edit -S -s -m "Release ${{ needs.build.outputs.appVersion }}"
          git push
      - name: Create Git tag
        id: git_tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true
          PRERELEASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [build, scan, bump]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ needs.build.outputs.gitTag }}
          name: ${{ needs.build.outputs.appVersion }} / ${{ needs.build.outputs.date }}
          bodyFile: CHANGELOG.md
