name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths: [src/**/*, main.py, requirements.txt, Dockerfile]

jobs:
  push_to_registries:
    name: Publish Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Log in to the GH Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Dry run for Git tag
        id: git_tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          DRY_RUN: true
          DEFAULT_BUMP: patch
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.git_tag.outputs.tag }}
            type=raw,value=latest
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Prepare job outputs
        id: op
        run: |
          echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
          echo "app_version=$(sed "s/^v//" <<< ${{ steps.git_tag.outputs.tag }})" >> "$GITHUB_OUTPUT"
    outputs:
       gitTag: ${{ steps.git_tag.outputs.tag }}
       appVersion: ${{ steps.op.outputs.app_version }}
       date: ${{ steps.op.outputs.date }}

  bump_version:
    name: Update VERSION file
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    needs:
      - push_to_registries
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Update VERSION file
        run: |
          echo ${{ needs.push_to_registries.outputs.appVersion }} > VERSION
          git commit -a --no-edit -S -s -m "Release ${{ needs.push_to_registries.outputs.appVersion }}"
          git push
      - name: Bump version and push tag
        id: git_tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true
          PRERELEASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    needs:
      - push_to_registries
      - bump_version
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Publish release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ needs.push_to_registries.outputs.gitTag }}
          name: ${{ needs.push_to_registries.outputs.appVersion }} / ${{ needs.push_to_registries.outputs.date }}
          bodyFile: CHANGELOG.md
